El-Psy-Congroo-T4/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls')),
]

main/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from main import views

urlpatterns = [

    url(r'^$', views.index.as_view(), name='index'),
    url(r'^login/$', views.Login.as_view(),name='login'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^signup/$', views.SignUp.as_view(),name='signup'),
    url(r'^vendedor/(?P<vendedor>.+)$', views.vendedorprofilepage, name='vendedorprofilepage'),
    url(r'^editar_perfil$', views.EditarPerfil.as_view(), name='editar_perfil'),
    url(r'^agregar_producto$', views.AgregarProducto.as_view(), name='agregar_producto'),
    url(r'^editar_producto/(?P<pid>[0-9]+)/$', views.EditarProducto.as_view(), name='editar_producto'),
    url(r'^eliminar_producto/(?P<pid>[0-9]+)/$', views.productos_delete, name='eliminar_producto'),
    url(r'^dashboard/$', views.Dashboard.as_view(), name='dashboard'),
    # ajax request to change vendedor active status
    url(r'^ajax/change_active/$', views.change_active, name='change_active'),
    url(r'^ajax/getStock/$', views.getStock, name='getStock'),
    url(r'^ajax/crearTransaccion/$', views.crearTransaccion, name='crearTransaccion'),
    # ajax request to add fav to user
    url(r'^ajax/add_favorite/$', views.add_favorite, name='add_favorite'),
    url(r'^ajax/alerta_policial/$', views.alerta_policial, name='alerta_policial'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/forms.py
from django import forms

from main.models import *


class Formulario_Registro(forms.Form):
    tipo_cuenta = forms.ChoiceField(label='Tipo de Usuario',
                                    choices=[(1, "Alumno"), (2, "Vendedor Fijo"), (3, "Vendedor Ambulante")])
    tipo = forms.ChoiceField(required=False)
    nombre = forms.CharField(label='Ingresa tu nombre')
    email = forms.EmailField(label='E-mail', widget=forms.EmailInput)
    contrasena = forms.CharField(label='Ingresa tu contraseña', widget=forms.PasswordInput)
    chequeo_contrasena = forms.CharField(label='Repite tu contraseña', widget=forms.PasswordInput)

    hora_inicio = forms.TimeField(label='Hora de apertura', widget=forms.TimeInput(), required=False, initial='8:00')
    hora_fin = forms.TimeField(label='Hora de cierre', widget=forms.TimeInput(), required=False, initial='18:00')

    latitud = forms.DecimalField(decimal_places=40, max_digits=42, widget=forms.HiddenInput(), initial='-33.457785')
    longitud = forms.DecimalField(decimal_places=40, max_digits=42, widget=forms.HiddenInput(), initial='-70.663808')

    pagos = forms.ModelMultipleChoiceField(queryset=FormasDePago.objects.all(), widget=forms.SelectMultiple(),
                                           required=False, initial=FormasDePago.objects.none())

    def limpiar_contrasena(self):
        if 'contrasena' in self.cleaned_data:
            contrasena = self.cleaned_data['password']
            chequeo_contrasena = self.cleaned_data['password_check']
            if contrasena == chequeo_contrasena:
                return chequeo_contrasena
        raise forms.ValidationError('Las contraseñas no coinciden')

    class Meta:
        model = Usuario
        fields = ('tipo', 'nombre', 'avatar')


class Formulario_Ingreso(forms.Form):
    correo = forms.EmailField(label='Ingresa tu e-mail', widget=forms.EmailInput)
    contrasena = forms.CharField(label='Ingresa tu contraseña', widget=forms.PasswordInput())


class Formulario_Actualizar_Perfil(forms.Form):
    nombre = forms.CharField(label='Editar nombre')
    email = forms.EmailField(label='Ingresa tu e-mail', widget=forms.EmailInput)
    avatar = forms.ImageField(label='Avatar', widget=forms.FileInput, required=False, initial=None)
    contrasena = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    pagos = forms.ModelMultipleChoiceField(queryset=FormasDePago.objects.all(), required=False,
                                           initial=FormasDePago.objects.none())
    hora_inicio = forms.TimeField(label='Hora de apertura', widget=forms.TimeInput(), required=False)
    hora_fin = forms.TimeField(label='Hora de cierre', widget=forms.TimeInput(), required=False)

    latitud = forms.DecimalField(decimal_places=40, max_digits=42, widget=forms.HiddenInput(), initial='-33.457785')
    longitud = forms.DecimalField(decimal_places=40, max_digits=42, widget=forms.HiddenInput(), initial='-70.663808')

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        if self.user is not None:
            inicial = 0
            final = 0
            if self.user.usuario.tipo == 2:
                inicial = Vendedor.objects.values_list('horario_inicio', flat=True).get(nombre=self.user.username)
                final = Vendedor.objects.values_list('horario_fin', flat=True).get(nombre=self.user.username)

            kwargs.update(initial={'email': self.user.email,
                                   'hora_inicio': inicial,
                                   'hora_fin': final})
        super(Formulario_Actualizar_Perfil, self).__init__(*args, **kwargs)

    class Meta:
        model = Usuario
        exclude = ('username', 'date_joined')


class Formulario_Producto(forms.ModelForm):
    imagen = forms.ImageField(label='Imagen', widget=forms.FileInput, required=False, initial=None)

    class Meta:
        model = Comida
        fields = ('nombre', 'precio', 'stock', 'categorias', 'descripcion')


class form_filtros(forms.Form):
    favoritos = forms.BooleanField(label='Favoritos', widget=forms.CheckboxInput, required=False)
    filtros = forms.MultipleChoiceField(label='Filtros', widget=forms.CheckboxSelectMultiple, choices=Categorias,
                                        required=False)

templates/refactoring/agregar-productos.html
{% extends 'refactoring/base.html' %}
{% load staticfiles %}

{% block content %}
    <script>
        $(document).ready(function() {
            $('select').material_select();
        });
    </script>

    <main>
        <div class="section"></div>

        <h4 class="teal-text" style="text-align: center;">Agregar Producto</h4>
        <div class="section"></div>

        <div class="container">
            <div class="z-depth-1 grey lighten-4 row" style="margin-left: 5%; margin-right: 5%; padding: 32px 48px 0px 48px; border: 1px solid #EEE;">

                <form class="col s12 m12" method="post" enctype="multipart/form-data" action="">
                    {% csrf_token %}
                    <div class='row'>
                        <div class='col s12 m12'>
                        </div>
                    </div>

                    {{ form.as_p }}

                    <div class='row'>
                        <button type='submit' class='col l5 offset-l4 btn btn-large waves-effect button teal'>&emsp; &emsp;Agregar<i class="material-icons right">send</i></button>
                    </div>

                </form>
            </div>
        </div>

    </main>
{% endblock %}

templates/refactoring/editar-perfil.html
{% extends 'refactoring/base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block content %}
    <style>
        #map {
            height: 400px;
        }
    </style>
    <script>
        $(document).ready(function () {
            $('select').material_select();
        });
    </script>

    <div class="section"></div>
    <main>
        <div class="section"></div>

        <h5 class="teal-text" style="text-align: center;">Editar Información</h5>
        <div class="section"></div>

        <div class="container">
            <div class="z-depth-1 grey lighten-4 row"
                 style="margin-left: 5%; margin-right: 5%; padding: 32px 48px 0px 48px; border: 1px solid #EEE;">

                <form class="col s12 m12" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class='row'>
                        <div class='col s12 m12'>
                        </div>
                    </div>
                    <div class='row'>
                        <div class='input-field col s12 m12'>
                            {#                            <h6>Editar nombre:</h6>#}
                            {{ form.nombre }}
                            <label style="text-align: center;" for='id_nombre'>Editar nombre</label>
                        </div>
                    </div>

                    <div class='row'>
                        <div class='input-field col s12 m12'>
                            {{ form.email }}
                            <label style="text-align: center" for='id_email'>Editar e-mail</label>
                        </div>
                    </div>

                    {#                    {% if userDj.usuario.tipo == 1 %}#}
                    {#                        <div class='row'>#}
                    {#                            <div class='input-field col s12 m12'>#}
                    {#<h6>Editar favoritos:</h6>#}
                    {#                                {{ form.favoritos }}#}
                    {#                                <label style="text-align: center;" for='id_favoritos'>Editar favoritos</label>#}
                    {#                            </div>#}
                    {#                        </div>#}
                    {#                    {% endif %}#}

                    {% if userDj.usuario.tipo == 2 %}

                        <div class="row">
                            <div class="col s12">
                                <div class="row">
                                    <div class="input-field col s6">
                                        <i class="material-icons prefix">alarm</i>
                                        {{ form.hora_inicio }}
                                        <label for="id_hora_inicio">Hora inicial</label>
                                    </div>
                                    <div class="input-field col s6">
                                        <i class="material-icons prefix">alarm</i>
                                        {{ form.hora_fin }}
                                        <label for="id_hora_fin">Hora final</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col s12">
                            Seleccione su ubicación:
                            {{ form.latitud }}
                            {{ form.longitud }}
                            <div id="map"></div>
                            <script>
                                var map;
                                function initMap() {
                                    map = new google.maps.Map(document.getElementById('map'), {
                                        center: {lat: -33.457785, lng: -70.663808},
                                        zoom: 19
                                    });
                                    var marker = new google.maps.Marker({
                                            position: {
                                                lat: -33.457785,
                                                lng: -70.663808
                                            },
                                            map: map
                                        }
                                    );
                                    google.maps.event.addListener(map, 'click', function (event) {
                                        placeMarker(event.latLng);
                                    });
                                    function placeMarker(location) {
                                        marker.setPosition(location);
                                        document.forms[0].id_latitud.value = location.lat();
                                        document.forms[0].id_longitud.value = location.lng();
                                    }
                                }
                            </script>
                            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBV7ElkwQIJ2v6YG9fhXsbxbHNZzfoO9L8&callback=initMap"
                                    async defer></script>

                        </div>
                    {% endif %}

                    {% if userDj.usuario.tipo == 2 or userDj.usuario.tipo == 3 %}
                        <div class='row'>
                            <div class='input-field col s12 m12'>
                                Seleccione sus formas de pago:
                                <div>
                                    {{ form.pagos }}
                                </div>
                            </div>
                        </div>
                    {% endif %}
                    <div>
                        Cambiar avatar:
                    </div>

                    <div class="input-field col s12 l6">
                        {{ form.avatar }}
                    </div>

                    <div class='row'>
                        <div class='input-field col s12 m12'>
                            {{ form.contrasena }}
                            <label style="text-align: center" for='id_contrasena'>Para confirmar, ingresa tu
                                contraseña</label>
                        </div>
                    </div>

                    <div class='row'>
                        <button type='submit' name='btn_login' class='col l6 offset-l3 btn btn-large waves-effect teal'>
                            Guardar cambios
                        </button>
                    </div>

                </form>
            </div>
        </div>

        <div class="section"></div>
        <div class="section"></div>
    </main>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.min.js"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
{% endblock %}

templates/refactoring/index.html
{% extends 'refactoring/base.html' %}
{% load staticfiles %}

{% block filtros_content %}
    <li><a class="subheader">Filtros</a></li>
    <form method="post" action="">
        {% csrf_token %}
        {% if userDj.is_authenticated %}
            {% if user.tipo == 1 %}
                <li>
                    <div class="switch" style="margin-left: 10px;">
                        <label for="id_favoritos">
                            <input id="id_favoritos" name="favoritos" type="checkbox" value="0">
                            <span class="lever"></span>Sólo mostrar favoritos
                        </label>
                    </div>
                </li>
                <li>
                    <div class="divider"></div>
                </li>
            {% endif %}
        {% endif %}

        <ul id="id_filtros">
            {% for choice, text in form.filtros.field.choices %}
                <li>
                    <div class="switch" style="margin-left: 10px;">
                        <label for="id_filtros_{{ forloop.counter0 }}">
                            <input id="id_filtros_{{ forloop.counter0 }}" name="filtros" type="checkbox"
                                   value="{{ forloop.counter0 }}">
                            <span class="lever"></span>{{ text }}
                        </label>
                    </div>
                </li>
            {% endfor %}
        </ul>
        <li>
            <div class='row center-align' style="margin-bottom: 100px;">
                <button type='submit' name='filtrar' class='btn btn-large waves-effect teal'>
                    Filtrar
                </button>
            </div>
        </li>
    </form>
{% endblock %}


{% block content %}
    <div id="map"></div>
    <script>
        function initMap() {
            var infoWindow;
            var beau850 = {lat: -33.457785, lng: -70.663808};
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 19,
                center: beau850
            });
            var markers = [];
            var infoWindows = [];
            var info = '';
            var estado = 'Activo';
            var pagos = '';
            var menu = '';
            var horario = '';
            {% for vendedor in vendedores %}
                markers.push(new google.maps.Marker({
                    position: {lat: {{ vendedor.lat }}, lng: {{ vendedor.long }}},
                    map: map
                    {% if vendedor in vendedores_favoritos %}
                        , icon: '../static/img/star.png'
                    {% endif %}
                }));
                {% if vendedor.activo %}
                    estado = 'Activo';
                {% else %}
                    estado = 'Inactivo';
                {% endif %}
                pagos = '';
                {% for forma in vendedor.formasDePago.all %}
                    {% if forloop.last %}
                        pagos += '{{ forma.forma }}.';
                    {% else %}
                        pagos += '{{ forma.forma }}, ';
                    {% endif %}
                {% endfor %}
                menu = '';
                {% for item in vendedor.vendedor_respectivo.all %}
                    {% if forloop.last %}
                        menu += '{{ item.nombre }}.';
                    {% else %}
                        menu += '{{ item.nombre }}, ';
                    {% endif %}
                {% endfor %}
                horario = '';
                {% if vendedor.usuario.tipo == 2 %}
                    horario = '<p><i>Horario:</i> {{ vendedor.horarioIni }} - {{ vendedor.horarioFin }}</p>';
                {% endif %}
                info = '<div id="content">' +
                    '<div id="siteNotice">' +
                    '</div>' +
                    '<div><p style="float: left;"><img src="/media/{{ vendedor.avatar }}" width="50" hspace="10"></p>' +
                    '<h4>{{ vendedor.nombre }}</h4></div>' +
                    '<p style="color:#029500;">' + estado + '</p>' +
                    '<div id="bodyContent">' +
                    '<p><i>Menú:</i> ' + menu + '</p>' + horario +
                    '<p><i>Formas de pago:</i> ' + pagos + '</p>' +
                    '<p style="text-align: right;">' +
                    '<a href="{% url 'vendedorprofilepage' vendedor=vendedor %}">Ver detalles»</a></p>' +
                    '</div>' +
                    '</div>';
                infoWindows.push(new google.maps.InfoWindow({
                    content: info,
                    maxWidth: 400
                }));
                markers[{{ forloop.counter0 }}].addListener('click', function () {
                    infoWindows[{{ forloop.counter0 }}].open(map, markers[{{ forloop.counter0 }}]);
                });
            {% endfor %}

            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function (position) {
                    var pos = {
                        lat: position.coords.latitude,
                        lng: position.coords.longitude
                    };
                    map.setCenter(pos);
                }, function () {
                    handleLocationError(true, infoWindow, map.getCenter());
                });
            } else {
                // Browser doesn't support Geolocation
                handleLocationError(false, infoWindow, map.getCenter());
            }
        }
        function handleLocationError(browserHasGeolocation, infoWindow, pos) {
            infoWindow.setPosition(pos);
            infoWindow.setContent(browserHasGeolocation ?
                'Error: The Geolocation service failed.' :
                'Error: Your browser doesn\'t support geolocation.');
            infoWindow.open(map);
        }
    </script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBV7ElkwQIJ2v6YG9fhXsbxbHNZzfoO9L8&callback=initMap">
    </script>

{% endblock %}

templates/refactoring/login.html
{% extends 'refactoring/base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="section"></div>
    <main>
        <div class="section"></div>

        <h5 style="text-align: center;" class="teal-text">Inicia Sesión</h5>
        <div class="section"></div>

        <div class="container">
            <div class="z-depth-1 grey lighten-4 row" style="margin-left: 5%; margin-right: 5%; padding: 32px 48px 0px 48px; border: 1px solid #EEE;">

                <form class="col s12" method="post" action="">
                    {% csrf_token %}
                    <div class='row'>
                        <div class='col s12'>
                        </div>
                    </div>

                    <div class='row'>
                        <div class='input-field col s12'>
                            <input class='validate' type='email' name='email' id='email' />
                            <label style="text-align: center;" for='id_email'>Ingresa tu correo</label>
                        </div>
                    </div>

                    <div class='row'>
                        <div class='input-field col s12'>
                            <input class='validate' type='password' name='password' id='password' />

                            <label style="text-align: center;" for='id_contrasena'>Ingresa tu contraseña</label>
                        </div>
                        <label style='float: right;'>
                            <a class='red-text text-accent-2' href='#!'><b>¿Olvidaste tu contraseña?</b></a>
                        </label>
                    </div>
                    <div class='row'>
                        <div class='col s12'>
                            <a class='red-text text-accent-2'><b>{{ error }}</b></a>

                        </div>
                    </div>


                    <div class='row'>
                        <input type="hidden" name="next" value="/" />
                        <button type='submit' name='btn_login' class='col l6 offset-l3 btn btn-large waves-effect teal'>Iniciar sesión</button>
                    </div>

                </form>
            </div>
        </div>
        <div style="text-align: center;"><a class="grey-text">¿Aún no tienes cuenta?</a> <a href="{% url 'signup' %}"> Regístrate</a></div>


        <div class="section"></div>
        <div class="section"></div>
    </main>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
{% endblock %}

templates/refactoring/signup.html
{% extends 'refactoring/base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
    <style>
        #map {
            height: 400px;
        }
    </style>
    <script>
        $(document).ready(function () {
            $('select').material_select();
        });
    </script>

    <div class="section"></div>
    <main>
        <div class="section"></div>

        <h5 class="teal-text" style="text-align: center;">¡Regístrate!</h5>
        <div class="section"></div>

        <div class="container">
            <div class="z-depth-1 grey lighten-4 row"
                 style="margin-left: 5%; margin-right: 5%; padding: 32px 48px 0px 48px; border: 1px solid #EEE;">

                <form class="col s12 m12" method="post" action="">
                    {% csrf_token %}
                    <div class='row'>
                        <div class='col s12 m12'>
                        </div>
                    </div>

                    <div class="input-field col s12 m12">
                        {{ form.tipo_cuenta }}
                        <label>Tipo de Usuario</label>
                    </div>

                    <div class='row'>
                        <div class='input-field col s12 m12'>
                            {{ form.nombre }}
                            <label style="text-align: center" for='id_nombre'>Ingresa tu nombre</label>
                        </div>
                    </div>

                    <div class="row">
                        <div class='input-field col s12 m12'>
                            {{ form.email }}
                            <label style="text-align: center" for='id_email'>Ingresa tu e-mail</label>
                        </div>
                    </div>

                    <div id="options">
                        <div class="row" id="fijo">
                            Seleccione su horario de atención:
                            <div class="col s12">
                                <div class="row">
                                    <div class="input-field col s6">
                                        <i class="material-icons prefix">alarm</i>
                                        {{ form.hora_inicio }}
                                        <label for="id_hora_inicio">Hora inicial</label>
                                    </div>
                                    <div class="input-field col s6">
                                        <i class="material-icons prefix">alarm</i>
                                        {{ form.hora_fin }}
                                        <label for="id_hora_fin">Hora final</label>
                                    </div>
                                </div>
                            </div>
                            <div class="col s12">
                                Seleccione su ubicación:
                                {{ form.latitud }}
                                {{ form.longitud }}
                                <div id="map"></div>
                                <script>
                                    var map;
                                    function initMap() {
                                        map = new google.maps.Map(document.getElementById('map'), {
                                            center: {lat: -33.457785, lng: -70.663808},
                                            zoom: 19
                                        });
                                        var marker = new google.maps.Marker({
                                                position: {
                                                    lat: -33.457785,
                                                    lng: -70.663808
                                                },
                                                map: map
                                            }
                                        );
                                        google.maps.event.addListener(map, 'click', function (event) {
                                            placeMarker(event.latLng);
                                        });
                                        function placeMarker(location) {
                                            marker.setPosition(location);
                                            document.forms[0].id_latitud.value = location.lat();
                                            document.forms[0].id_longitud.value = location.lng();
                                        }
                                    }
                                </script>
                                <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBV7ElkwQIJ2v6YG9fhXsbxbHNZzfoO9L8"></script>

                            </div>
                        </div>

                        <div class='row' id="ambulante">
                            <div class='input-field col s12 m12'>
                                Seleccione sus formas de pago:
                                {{ form.pagos }}
                            </div>
                        </div>
                    </div>

                    <div class='row'>
                        <div class='input-field col s12 m12'>
                            {{ form.contrasena }}
                            <label style="text-align: center" for='id_contrasena'>Ingresa tu contraseña</label>
                        </div>
                    </div>

                    <div class='row'>
                        <div class='input-field col s12 m12'>
                            {{ form.chequeo_contrasena }}
                            <label style="text-align: center" for='id_chequeo_contrasena'>Repite tu contraseña</label>
                        </div>
                    </div>
                    <div class='row'>
                        <div class='col s12'>
                            <a class='red-text text-accent-2'><b>{{ mensage }}</b></a>

                        </div>
                    </div>

                    <div class='row'>
                        <button type='submit' name='btn_login' class='col l6 offset-l3 btn btn-large waves-effect teal'>
                            Registrarse
                        </button>
                    </div>

                </form>
            </div>
        </div>
        <div style="text-align: center;"><a class="grey-text"> ¿Ya tienes una cuenta? </a></a><a
                href="{% url 'login' %}">
            Inicia sesión</a>
        </div>


        <div class="section"></div>
        <div class="section"></div>
    </main>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.min.js"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
    <script type="text/javascript">
        $('#options div').hide();
        $('#id_tipo_cuenta').change(refresh_inputs);
        refresh_inputs();
        function refresh_inputs() {
            var name = $('#id_tipo_cuenta').attr('name');
            var val = $('#id_tipo_cuenta').val();
            console.log(val);
            if (val.localeCompare("3") == 0) {
                $('#options div').show();
                $('#fijo').hide();
            }
            if (val.localeCompare("2") == 0) {
                $('#options div').show();
                initMap();
            }
            if (val.localeCompare("1") == 0) {
                $('#options div').hide();
            }
        }
    </script>

{% endblock %}